### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-18: ordinal not in range(128)

### ISSUE THREAD

**Issue by rodrigo-rafael** [evidens/json2csv#10]
I have been facing this error:

Traceback (most recent call last):
  File "json2csv.py", line 155, in <module>
    loader.write_csv(filename=outfile, make_strings=args.strings)
  File "json2csv.py", line 105, in write_csv
    writer.writerows(out)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 154, in writerows
    return self.writer.writerows(rows)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-18: ordinal not in range(128)

how i solved it (return unicode(item).encode("utf-8")):

    def make_string(self, item):
        if isinstance(item, list) or isinstance(item, set) or isinstance(item, tuple):
            return self.SEP_CHAR.join([self.make_string(subitem) for subitem in item])
        elif isinstance(item, dict):
            return self.DICT_OPEN + self.DICT_SEP_CHAR.join([self.KEY_VAL_CHAR.join([k, self.make_string(val)]) for k, val in item.items()]) + self.DICT_CLOSE
        else:
            return unicode(item).encode("utf-8")

**Comment by evidens** [comment]
Did you install unicode CSV?

If you are working with unicode data you need to install the unicodecsv package as stated in the requirements.txt
