### ISSUE TITLE
Error:  ...File "json2csv.py", line 82 for k, val in row.items()})

### ISSUE THREAD

**Issue by blacknred0** [evidens/json2csv#15]
Ok, I am either doing something wrong, or there is something wrong with the code :/.

I am literally testing the code by using the following as example.
"testfile.json"
```
{
  "nodes": [
    {"source": {"author": "Someone"}, "message": {"original": "Hey!", "Revised": "Hey yo!"}},
    {"source": {"author": "Another"}, "message": {"original": "Howdy!", "Revised": "Howdy partner!"}},
    {"source": {"author": "Me too"}, "message": {"original": "Yo!", "Revised": "Yo, 'sup?"}}
  ]
}
```
Then I am creating the outline file with the following piece of code 
```
    python gen_outline.py --collection nodes /home/irving/workspace/json2csv_2/testfile.json -o /home/irving/workspace/json2csv_2/testfile_outline.json 
```

Granted the results of "testfile_outline.json" are not the same as what it is on the "README.md", but I kept on going.

Now, everything is good and dandy, and I decide to create the CSV.  So I type the following piece of code.
```
    python json2csv.py /home/irving/workspace/json2csv_2/testfile.json /home/irving/workspace/json2csv_2/testfile_outline.json -o /home/irving/workspace/json2csv_2/testfile.csv
```

This give me the following error
```
    File "json2csv.py", line 82
    for k, val in row.items()})
    ^
    SyntaxError: invalid syntax
```
What am I doing wrong?  Thoughts?
(By the way I did test the outline JSON from "README.md" and got same results)

**Comment by evidens** [comment]
Which version of Python are you using? I wrote this targeting python2.7

**Comment by blacknred0** [comment]
I think I might off missed that on the documentation, since I am running
it on python 2.6.6.

I'll upgrade to 2.7 and see if the problem goes away.

Thank you,

Irving Duran

**Comment by blacknred0** [comment]
Upgraded to python 2.7 and it works like a charm.  Thanks for the share!
