### ISSUE TITLE
Adding a open source licence

### ISSUE THREAD

**Issue by vnachank** [evidens/json2csv#16]
Hi Gabriel,
I came across this library when research over nested json to csv conversion library, this covers all the use-cases that we want to address. I would like to use this in our application but there is no licence as well as releases for it. It would be really helpful if you could add those to these repository as it will make it easier for others to use this tool.
 I apologize for contacting you over an issue as I couldn't find your email. Looking forward to your response.

Thanks,
Vaibhav

**Comment by evidens** [comment]
Fair point! I've gone with an MIT license because I wouldn't want to interfere with any use. That said, if you do make improvements, please consider contributing them back to this repo so other people can benefit.
Thank you,
Gabriel
