### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by putrasurya** [evidens/json2csv#27]
Traceback (most recent call last):
  File "json2csv.py", line 155, in <module>
    loader.write_csv(filename=outfile, make_strings=args.strings)
  File "json2csv.py", line 105, in write_csv
    writer.writerows(out)
  File "/usr/lib/python2.7/csv.py", line 158, in writerows
    return self.writer.writerows(rows)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 0: ordinal not in range(128)

**Comment by evidens** [comment]
You need to install the unicodecsv package. That's what you're installing with pip as directed in the README. 
		_____________________________

**Comment by putrasurya** [comment]
thank you! it's worked :)

**Comment by sjb554** [comment]
Hi, I am getting similar errors for various characters such as "â€™", "#", and "Â½" in my JSON files.

When I first installed, I used:

git clone https://github.com/evidens/json2csv.git
cd json2csv
pip install -r requirements.txt

But I am still getting the errors.  How do I check to make sure I have the unicodecsv package?

Thanks!
