### ISSUE TITLE
Dealing with properties that are array

### ISSUE THREAD

**Issue by GustavoRPS** [evidens/json2csv#3]
I wonder if there is some way or intention to handle properties that are array.

To convert this:

``` json
[ 
  {
    "autor": "Some autor",
    "data_protocolo": "26/02/1953",
    "data_publicacao_dpc": "26/02/1953",
    "descricao": "Description",
    "proposicao": "PL 2/1953",
    "fases": [
      {
        "acao": "Prosseguir",
        "data_envio": "11/09/1953 00:00:00",
        "data_recebimento": "11/09/1953 00:00:00",
        "despacho": "Lei",
        "nome": "Protocolo",
        "setor": "Plenário"
      },
      {
        "acao": "Prosseguir",
        "data_envio": "",
        "data_recebimento": "26/02/1953 00:00:00",
        "despacho": "",
        "nome": "Protocolo",
        "setor": "Plenário"
      }
    ]
  }
]
```

to this 

| autor | data_protocolo | data_publicacao_dpc | descricao | proposicao | fases.acao | fases.data_envio | fases.data_recebimento | fases.despacho | fases.nome | fases.setor |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Algum Autor | 26/02/1953 | 26/02/1953 | Description | PL 2/1953 | Prosseguir | 11/09/1953 00:00:00 | 11/09/1953 00:00:00 | Lei | publicada no D.O. de 11/09/1953. | Protocolo |
| Algum Autor | 26/02/1953 | 26/02/1953 | Description | PL 2/1953 | Prosseguir |  | 26/02/1953 00:00:00 |  | Protocolo | Plenário |

**Comment by evidens** [comment]
I refactored the outline loading and row processing so it could be used recursively.

I think the next step would be to define an updated outline schema (see nested schema)

In the updated schema, all map items would become dict elements (`key` would become optional (since we're often repeating it for header) and then we can test for a map/collection in `process_key_map` and in `process_each` and recursively iterated through nested outlines and data.

It would mean that in `process_each` you'd need to keep one copy of 'outer' data, and then after processing all the rows of the 'inner' data, merge each of the inner rows with the outer row data before continuing to the next row.

Hopefully that makes sense and you can move forward with that. I won't have much time to look into this in the next week.

**Comment by Manoj-Nagarajan** [comment]
Is there any way to convert below Json data to csv file ?

{
  "NasFilers": [
    {
      "id": "a8a7713f4ac54f67b74716c03e52d3bd",
      "name": "eag-laborf-2240-1",
      "firstDiscovered": "2015-08-20T21:51:59.389Z",
      "lastDiscovered": "2015-11-20T05:00:32.084Z",
      "lastChanged": "2015-09-30T20:43:17.024Z",
      "resourceType": "NasFiler",
      "source": "DFM",
      "fqdn": "test",
      "dfm": {
        "id": "1531d65c1fc64a65ba14b910468ec113",
        "name": "dfm_sapip.amers1.cis.trcloud",
        "url": "test_infotest_info.json"
      },
      "firmwareVersion": "8.3.0",
      "osVersion": "8.2.3P5 7-Mode",
      "manufacture": "NetApp",
      "model": "unknown",
      "serialNumber": "700000960543",
      "backup": true,
      "licenseISCSI": true,
      "licenseNFS": true,
      "licenseSnapMirror": true,
      "licenseSnapVault": true,
      "virtualFilers": [
        {
          "id": "b19fa78d585f4ed99f926bd5615a98b0",
          "name": "lab-test-e0015",
          "url": "test_date/b19fa78d585f4ed99f926bd5615a98b0.json"
        },
        {
          "id": "df70462070834a19a83532d77b6c3f26",
          "name": "eag-nasor-bkp06",
          "url": "test_date/df70462070834a19a83532d77b6c3f26.json"
        },
        {
          "id": "86fb732f59964908b5dbae88f0e55893",
          "name": "eag-nasor-bkp02",
          "url": "test_date/86fb732f59964908b5dbae88f0e55893.json"
        },
        {
          "id": "d3e4813c8e674f7f8f2d201d2a3644b3",
          "name": "eag-nasor-bkp03",
          "url": "test_date/d3e4813c8e674f7f8f2d201d2a3644b3.json"
        },
        {
          "id": "5f4c5dbbf7f84edc887982305761ddbd",
          "name": "eag-nasor-bkp01-vsip",
          "url": "test_date/5f4c5dbbf7f84edc887982305761ddbd.json"
        },
        {
          "id": "65f79f734ddf4c5ca7d5ac5da00dd2d4",
          "name": "vfiler0",
          "url": "test_date/65f79f734ddf4c5ca7d5ac5da00dd2d4.json"
        },
        {
          "id": "e4dd36f25f5b4428b8bfc11c30e93616",
          "name": "eag-nasor-bkp01",
          "url": "test_date/e4dd36f25f5b4428b8bfc11c30e93616.json"
        },
        {
          "id": "e2a212ae7b77416899c788f6229753c1",
          "name": "si-bkptest-001",
          "url": "test_date/e2a212ae7b77416899c788f6229753c1.json"
        },
        {
          "id": "6cb4fdfb89f34317b64f1140e8bc0630",
          "name": "cis-si-bkp-e01",
          "url": "test_date/6cb4fdfb89f34317b64f1140e8bc0630.json"
        }
      ],
      "aggregates": [
        {
          "id": "40171af92a98478dbe645ad2fce203ac",
          "name": "aggr1_thin",
          "url": "test/40171af92a98478dbe645ad2fce203ac.json"
        }
      ],
      "diskShelves": [
        {
          "id": "f8000b9d56a444e7a54e656f68705672",
          "name": "SHJMS0000000771",
          "url": "test_info/test/NasDiskShelves/f8000b9d56a444e7a54e656f68705672.json"
        },
        {
          "id": "f73a29474b0a4b6ba9e3ee9c01d44ccc",
          "name": "SHU0979752NMELS",
          "url": "test_info/test/NasDiskShelves/f73a29474b0a4b6ba9e3ee9c01d44ccc.json"
        }
      ],
      "interfaces": [
        {
          "id": "5369d395c06e40f69242b8d265018a76",
          "name": "e0M",
          "url": "test_info/test_info/5369d395c06e40f69242b8d265018a76.json"
        },
        {
          "id": "bf06547f99f345e1997ac432a7a6e3e8",
          "name": "e0P",
          "url": "test_info/test_info/bf06547f99f345e1997ac432a7a6e3e8.json"
        },
        {
          "id": "2cbd8e4ff1144496bada6003a42a802e",
          "name": "e0a",
          "url": "test_info/test_info/2cbd8e4ff1144496bada6003a42a802e.json"
        },
        {
          "id": "8bdab6577927424eade8fd7b5a4d7fe8",
          "name": "e0b",
          "url": "test_info/test_info/8bdab6577927424eade8fd7b5a4d7fe8.json"
        },
        {
          "id": "9952bcea1ca64365ae3d79cc16a2dc02",
          "name": "e0c",
          "url": "test_info/test_info/9952bcea1ca64365ae3d79cc16a2dc02.json"
        },
        {
          "id": "34573a862d074412a3ef683625eea5ef",
          "name": "e0d",
          "url": "test_info/test_info/34573a862d074412a3ef683625eea5ef.json"
        },
        {
          "id": "7e47c722263e45449ae7839693610c39",
          "name": "e1a",
          "url": "test_info/test_info/7e47c722263e45449ae7839693610c39.json"
        },
        {
          "id": "0ebd917852e341ceb880fc50164cb3fa",
          "name": "e1b",
          "url": "test_info/test_info/0ebd917852e341ceb880fc50164cb3fa.json"
        }
      ],
      "bondedInterfaces": [
        {
          "id": "8f14400e722c4ddab42372b5d7434bae",
          "name": "laborvif0",
          "url": "test_info/test/NasEthernetBonds/8f14400e722c4ddab42372b5d7434bae.json"
        }
      ],
      "ipspaces": [
        {
          "id": "9ab4690b3ee0454c97dd88f2420b68fc",
          "name": "or-ip2",
          "url": "test_info/test/NasIpSpaces/9ab4690b3ee0454c97dd88f2420b68fc.json"
        },
        {
          "id": "eb187cfba18c4652b04ada541d149d0a",
          "name": "or-ip1",
          "url": "test_info/test.json"
        }
      ]
    }
  ]
}

**Comment by evidens** [comment]
I'm curious why you need this information as a CSV? It seems like JSON is a better format for such nested and heterogenous data.

You might be better served by figuring out your purpose and what you need the data to look like and filter out some of the complexity if you don't need it. If you could transform it to CSV what would it look like? What information is relevant?

**Comment by Manoj-Nagarajan** [comment]
Thanks for your response.  I am working on a Integration solution where we have to read data from API in JSON format and convert to csv file. Once CSV file is available in server, we will load the data in Database using ETL tools and call DB Procedure to process data in Database and update in the target database.

**Comment by evidens** [comment]
Assuming `NasFilers` is the top key, you specify that as the collection, then you can specify `virtualFilers.0.id`, `virtualFilers.1.id`, … but CSV is really meant to be a fixed format so unless the items in the array reach a maximum. If you don't care about the atomic data inside each array element, you can use the `--strings` option to output the values as stringified JSON.

I think you need to be really clear on the target schema for the data you're trying to load. If you have an idea of how that will happen, you can likely use the outline format to represent what you need.

Are there no ETL tools that will load straight from JSON? Either way I think your schema is what you really need to figure out.

**Comment by Manoj-Nagarajan** [comment]
sure.Thanks a lot for your suggestion. I will try passing NasFiler as top key.

I am very new to Python scripting and will see how it can done using outline format,

We have a ETL tool to load JSON to CSV format, but then in our case we have to read url ( "test_date/b19fa78d585f4ed99f926bd5615a98b0.json", where test_date is the ipaddress) from VirtualFiler and read the next json data and convert to csv file.

Reading the url under virtualFilers and reading json data is not possible with our ETL Tool, so we are using python scripting for our solution.


 "virtualFilers": [
        {
          "id": "b19fa78d585f4ed99f926bd5615a98b0",
          "name": "lab-test-e0015",
          "url": "test_date/b19fa78d585f4ed99f926bd5615a98b0.json"
        },


Thanks again.

**Comment by Manoj-Nagarajan** [comment]
Hello... i was able to convert json file to a csv file using the steps in the read me file. Thanks a lot for sharing the same. When i convert the json to csv, the output is stored in alphabetical order. Is there any way, which can convert to same order as the soure...

Example :  
Source : id, name ,b1_test, url, a1_test . Result is stored in below format in csv file.

Result : a1_test, b1_test, id, name , url

But i want the output csv in below format.

Result : id, name ,b1_test, url, a1_test. 

Can you suggest if the same is possible . Thank you in advance...
